# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-15 14:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customauth', '0002_auto_20160115_1256'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='daily_computation_time',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_api_call',
        ),
        migrations.RemoveField(
            model_name='user',
            name='tok',
        ),
        migrations.RemoveField(
            model_name='user',
            name='used_computation_time',
        ),
    ]
