# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-15 11:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(blank=True, max_length=200, null=True, verbose_name='token')),
                ('daily_computation_time', models.IntegerField(default=0, verbose_name='daily computation time')),
                ('used_computation_time', models.IntegerField(default=0, verbose_name='used computation time')),
                ('last_api_call', models.DateTimeField(default=django.utils.timezone.now, verbose_name='last api call')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
