# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-15 14:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='last_solution',
            field=models.TextField(null=True, verbose_name='last calculated solution'),
        ),
        migrations.AddField(
            model_name='token',
            name='last_supplied_problem',
            field=models.TextField(null=True, verbose_name='last supplied problem'),
        ),
    ]
