# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-15 15:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20160115_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='last_solution',
            field=models.TextField(default='', null=True, verbose_name='last calculated solution'),
        ),
        migrations.AlterField(
            model_name='token',
            name='last_supplied_problem',
            field=models.TextField(default='{\n\t"variables":[],\n\t"parameters":[],\n\t"constraints":[],\n\t"objective":[]\n}', null=True, verbose_name='last supplied problem'),
        ),
    ]
