# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-14 09:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webinterface', '0002_auto_20160114_1032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='last_call',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
