# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-14 11:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webinterface', '0003_auto_20160114_1040'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
